<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

           <xs:element name="en4b5k_vendeglatas">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="etterem" type="etteremTipus" maxOccurs="unbounded"></xs:element>
                        <xs:element name="foszakacs" type="foszakacsTipus" maxOccurs="unbounded"></xs:element>
                        <xs:element name="szakacs" type="szakacsTipus" maxOccurs="unbounded"></xs:element>
                        <xs:element name="gyakornok" type="gyakornokTipus" maxOccurs="unbounded"></xs:element>
                        <xs:element name="vendeg" type="vendegTipus" maxOccurs="unbounded"></xs:element>
                        <xs:element name="rendeles" type="rendelesTipus" maxOccurs="unbounded"></xs:element>
                    </xs:sequence>
                </xs:complexType>

                <xs:key name="etterem_kulcs">
                        <xs:selector xpath="etterem"></xs:selector>
                        <xs:field xpath="@ekod"></xs:field>
                </xs:key>
                
                <xs:key name="foszakacs_kulcs">
                        <xs:selector xpath="etterem"></xs:selector>
                        <xs:field xpath="@ekod"></xs:field>
                </xs:key>



                <xs:keyref refer="etterem_kulcs" name="etterem_idegen_kulcs">
                <xs:selector xpath="rendeles"></xs:selector>
                <xs:field xpath="@e_v_e"></xs:field>
                </xs:keyref>

                <xs:keyref refer="vendeg_kulcs" name="vendeg_idegen_kulcs">
                <xs:selector xpath="rendeles"></xs:selector>
                <xs:field xpath="@e_v_v"></xs:field>
                </xs:keyref>

                <xs:unique name="unique_foszakacs">
                    <xs:selector xpath="foszakacs"></xs:selector>
                    <xs:field xpath="@e_f"></xs:field>
                </xs:unique>
           </xs:element>


        <xs:complexType name="etteremTipus">
           <xs:sequence>
            <xs:element name="nev" type="xs:string"></xs:element>
            <xs:element name="cim" type="cimTipus"></xs:element>
            <xs:element name="csillag" type="xs:integer"></xs:element>
            </xs:sequence>
       </xs:complexType>

       <xs:complexType name="cimTipus">
           <xs:sequence>
            



            </xs:sequence>
       </xs:complexType>

       <xs:complexType name="gyakornokTipus">
           <xs:sequence>
            <xs:element name="nev" type="xs:string"></xs:element>
            <xs:element name="gyakorlat" type="gyakorlatTipus"></xs:element>
            
            </xs:sequence>
       </xs:complexType>

       <xs:complexType name="rendelesTipus">
           <xs:sequence>
            <xs:element name="osszeg" type="xs:string"></xs:element>
            <xs:element name="etel" type="xs:integer"></xs:element>
            </xs:sequence>
            <xs:attribute name="e_v_e" type="xs:string" use="required"></xs:attribute>
            <xs:attribute name="e_v_v" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
</xs:schema>