<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="unqualified">

  <xs:element name="orarend">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ora" type="oraTípus" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="oraTípus">
    <xs:sequence>
      <xs:element name="targy" type="xs:string"/>
      <xs:element name="idopont" type="idopontTípus" minOccurs="0"/>
      <xs:element name="helyszin" type="xs:string" minOccurs="0"/>
      <xs:element name="oktato" type="xs:string"/>
      <xs:element name="szak" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute name="típus" type="oraTípusTípus" use="optional" default="elmelet"/>
  </xs:complexType>

  <xs:simpleType name="oraTípusTípus">
    <xs:restriction base="xs:string">
      <xs:enumeration value="elmelet"/>
      <xs:enumeration value="gyakorlat"/>
      <xs:enumeration value="CV"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="napTípus">
    <xs:restriction base="xs:string">
      <xs:enumeration value="hétfő"/>
      <xs:enumeration value="kedd"/>
      <xs:enumeration value="szerda"/>
      <xs:enumeration value="csütörtök"/>
      <xs:enumeration value="péntek"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="idopontTípus">
    <xs:sequence>
      <xs:element name="nap" type="napTípus"/>
      <xs:element name="tol" type="idopontOraTípus"/>
      <xs:element name="ig" type="idopontOraTípus"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="idopontOraTípus">
    <xs:restriction base="xs:positiveInteger">
      <xs:minInclusive value="8"/>
      <xs:maxInclusive value="20"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>
